// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef UserInterface_h
#define UserInterface_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
extern void preview_cb(Fl_Button*, void*);
#include <FL/Fl_Choice.H>
#include <FL/Fl_Input.H>
extern void startStream_cb(Fl_Button*, void*);
#include <FL/Fl_Text_Display.H>

class UserInterface {
public:
  UserInterface();
  Fl_Double_Window *mainWindow;
  Fl_Group *inputGroup;
  Fl_Button *previewSourceBtn;
  Fl_Choice *ndiSourceSelect;
  Fl_Group *encodeGroup;
  Fl_Choice *codecSelect;
  static Fl_Menu_Item menu_codecSelect[];
  static Fl_Menu_Item *h264CodecChoice;
  static Fl_Menu_Item *h265CodecChoice;
  static Fl_Menu_Item *av1CodecChoice;
  Fl_Group *outputGroup;
  Fl_Input *ristAddressInput;
  Fl_Input *ristPortInput;
  Fl_Input *ristBufferInput;
  Fl_Input *ristBandwidthInput;
  Fl_Text_Display *logDisplay;
  void show(int argc, char **argv);
};
#endif
