// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef UserInterface_h
#define UserInterface_h
#include <FL/Fl.H>
#include "common.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>
extern void save_settings_cb(Fl_Menu_*, void*);
extern void load_settings_cb(Fl_Menu_*, void*);
#include <FL/Fl_Group.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Button.H>
extern void refreshSources_cb(Fl_Button*, void*);
extern void select_codec_cb(Fl_Menu_*, long);
extern void select_encoder_cb(Fl_Menu_*, long);
#include <FL/Fl_Input.H>
extern void encoder_bitrate_cb(Fl_Input*, void*);
extern void rist_address_cb(Fl_Input*, void*);
#include <FL/Fl_Check_Button.H>
extern void use_rpc_cb(Fl_Check_Button*, void*);
extern void upscale_cb(Fl_Check_Button*, void*);
extern void reencodeBitrate_cb(Fl_Input*, void*);
extern void rist_streams_cb(Fl_Input*, void*);
extern void streamDestinationsButton_cb(Fl_Button*, void*);
extern void rist_bandwidth_cb(Fl_Input*, void*);
extern void rist_buffer_min_cb(Fl_Input*, void*);
extern void rist_buffer_max_cb(Fl_Input*, void*);
extern void rist_rtt_min_cb(Fl_Input*, void*);
extern void rist_rtt_max_cb(Fl_Input*, void*);
extern void rist_reorder_buffer_cb(Fl_Input*, void*);
extern void startStream_cb(Fl_Button*, void*);
extern void stopStream_cb(Fl_Button*, void*);
#include <FL/Fl_Output.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Window.H>
extern void addDestinationButton_cb(Fl_Button*, void*);
extern void closeDestinationsButton_cb(Fl_Button*, void*);
#include <FL/Fl_Browser.H>
extern void editDestinationButton_cb(Fl_Button*, void*);
extern void removeDestinationButton_cb(Fl_Button*, void*);
extern void updateDestinationButton_cb(Fl_Button*, void*);
extern void cancelUpdateDestinationButton_cb(Fl_Button*, void*);

class UserInterface {
public:
  UserInterface();
  Fl_Double_Window *mainWindow;
  Fl_Menu_Bar *topMenu;
  static Fl_Menu_Item menu_topMenu[];
  static Fl_Menu_Item *saveSettingsMenuItem;
  static Fl_Menu_Item *loadSettingsMenuItem;
  Fl_Group *inputGroup;
  Fl_Choice *ndiSourceSelect;
  Fl_Button *btnRefreshSources;
  Fl_Group *encodeGroup;
  Fl_Choice *codecSelect;
  static Fl_Menu_Item menu_codecSelect[];
  static Fl_Menu_Item *h264CodecChoice;
  static Fl_Menu_Item *h265CodecChoice;
  static Fl_Menu_Item *av1CodecChoice;
  Fl_Choice *encoderSelect;
  static Fl_Menu_Item menu_encoderSelect[];
  static Fl_Menu_Item *softwareEncoderChoice;
  static Fl_Menu_Item *amdEncoderChoice;
  static Fl_Menu_Item *qsvEncoderChoice;
  static Fl_Menu_Item *nvencEncoderChoice;
  Fl_Input *encoderBitrateInput;
  Fl_Input *ristAddressInput;
  Fl_Check_Button *useRpcInput;
  Fl_Check_Button *upscaleInput;
  Fl_Input *reencodeBitrateInput;
  Fl_Input *ristStreamCount;
  Fl_Button *streamDestinationsButton;
  Fl_Input *ristBandwidthInput;
  Fl_Input *ristBufferMinInput;
  Fl_Input *ristBufferMaxInput;
  Fl_Input *ristRttMinInput;
  Fl_Input *ristRttMaxInput;
  Fl_Input *ristReorderBufferInput;
  Fl_Button *btnStartStream;
  Fl_Button *btnStopStream;
  Fl_Group *statsGroup;
  Fl_Output *bandwidthOutput;
  Fl_Output *linkQualityOutput;
  Fl_Output *retransmittedPacketsOutput;
  Fl_Output *rttOutput;
  Fl_Output *totalPacketsOutput;
  Fl_Output *encodeBitrateOutput;
  Fl_Group *totalStatsGroup;
  Fl_Output *cumulativeBandwidthOutput;
  Fl_Output *cumulativeRetransmittedPacketsOutput;
  Fl_Output *cumulativeTotalPacketsOutput;
  Fl_Output *cumulativeEncodeBitrateOutput;
  Fl_Text_Display *logDisplay;
  Fl_Text_Display *ristLogDisplay;
  Fl_Window *destinationsDialog;
  Fl_Input *serverAddressInput;
  Fl_Input *streamKeyInput;
  Fl_Button *addDestinationButton;
  Fl_Button *closeDestinationsButton;
  Fl_Browser *destinationListBrowser;
  Fl_Button *editDestinationButton;
  Fl_Button *removeDestinationButton;
  Fl_Button *updateDestinationButton;
  Fl_Button *cancelUpdateDestinationButton;
  void show(int argc, char **argv);
};
#endif
