// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "UserInterface.h"

Fl_Menu_Item UserInterface::menu_codecSelect[] = {
 {"H264", 0,  (Fl_Callback*)select_codec_cb, (void*)("h264"), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"H265", 0,  (Fl_Callback*)select_codec_cb, (void*)("h265"), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"AV1", 0,  (Fl_Callback*)select_codec_cb, (void*)("av1"), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};
Fl_Menu_Item* UserInterface::h264CodecChoice = UserInterface::menu_codecSelect + 0;
Fl_Menu_Item* UserInterface::h265CodecChoice = UserInterface::menu_codecSelect + 1;
Fl_Menu_Item* UserInterface::av1CodecChoice = UserInterface::menu_codecSelect + 2;

Fl_Menu_Item UserInterface::menu_encoderSelect[] = {
 {"Software", 0,  (Fl_Callback*)select_encoder_cb, (void*)("software"), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"AMD", 0,  (Fl_Callback*)select_encoder_cb, (void*)("amd"), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Intel QSV", 0,  (Fl_Callback*)select_encoder_cb, (void*)("qsv"), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Nvidia NVENC", 0,  (Fl_Callback*)select_encoder_cb, (void*)("nvenc"), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};
Fl_Menu_Item* UserInterface::softwareEncoderChoice = UserInterface::menu_encoderSelect + 0;
Fl_Menu_Item* UserInterface::amdEncoderChoice = UserInterface::menu_encoderSelect + 1;
Fl_Menu_Item* UserInterface::qsvEncoderChoice = UserInterface::menu_encoderSelect + 2;
Fl_Menu_Item* UserInterface::nvencEncoderChoice = UserInterface::menu_encoderSelect + 3;

UserInterface::UserInterface() {
  { mainWindow = new Fl_Double_Window(1330, 610, "NDI RIST Encoder");
    mainWindow->user_data((void*)(this));
    { inputGroup = new Fl_Group(35, 25, 235, 99, "Input");
      { ndiSourceSelect = new Fl_Choice(104, 32, 140, 22, "NDI Source");
        ndiSourceSelect->down_box(FL_BORDER_BOX);
      } // Fl_Choice* ndiSourceSelect
      { previewSourceBtn = new Fl_Button(64, 92, 185, 22, "Preview Source");
        previewSourceBtn->callback((Fl_Callback*)preview_cb);
      } // Fl_Button* previewSourceBtn
      { btnRefreshSources = new Fl_Button(64, 62, 185, 22, "Refresh Sources");
        btnRefreshSources->callback((Fl_Callback*)refreshSources_cb);
      } // Fl_Button* btnRefreshSources
      inputGroup->end();
    } // Fl_Group* inputGroup
    { encodeGroup = new Fl_Group(26, 143, 249, 97, "Encode");
      { codecSelect = new Fl_Choice(140, 148, 92, 22, "Codec");
        codecSelect->down_box(FL_BORDER_BOX);
        codecSelect->menu(menu_codecSelect);
      } // Fl_Choice* codecSelect
      { encoderSelect = new Fl_Choice(141, 173, 92, 22, "Encoder");
        encoderSelect->down_box(FL_BORDER_BOX);
        encoderSelect->menu(menu_encoderSelect);
      } // Fl_Choice* encoderSelect
      { encoderBitrateInput = new Fl_Input(141, 196, 90, 24, "Video Bitrate");
        encoderBitrateInput->callback((Fl_Callback*)encoder_bitrate_cb);
      } // Fl_Input* encoderBitrateInput
      encodeGroup->end();
    } // Fl_Group* encodeGroup
    { Fl_Group* o = new Fl_Group(390, 33, 218, 77, "Output");
      { ristAddressInput = new Fl_Input(390, 33, 218, 22, "RIST Address");
        ristAddressInput->callback((Fl_Callback*)rist_address_cb);
      } // Fl_Input* ristAddressInput
      { rtmpAddressInput = new Fl_Input(390, 60, 218, 22, "RTMP Server");
        rtmpAddressInput->callback((Fl_Callback*)rtmp_address_cb);
      } // Fl_Input* rtmpAddressInput
      { rtmpKeyInput = new Fl_Input(390, 88, 218, 22, "RTMP Key");
        rtmpKeyInput->callback((Fl_Callback*)rtmp_key_cb);
      } // Fl_Input* rtmpKeyInput
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(765, 28, 95, 149, "RIST Settings");
      { ristBandwidthInput = new Fl_Input(765, 28, 92, 22, "Bandwidth");
        ristBandwidthInput->callback((Fl_Callback*)rist_bandwidth_cb);
      } // Fl_Input* ristBandwidthInput
      { ristBufferMinInput = new Fl_Input(765, 53, 92, 22, "Buffer Min");
        ristBufferMinInput->callback((Fl_Callback*)rist_buffer_min_cb);
      } // Fl_Input* ristBufferMinInput
      { ristBufferMaxInput = new Fl_Input(765, 78, 92, 22, "Buffer Max");
        ristBufferMaxInput->callback((Fl_Callback*)rist_buffer_max_cb);
      } // Fl_Input* ristBufferMaxInput
      { ristRttMinInput = new Fl_Input(765, 103, 92, 22, "RTT Min");
        ristRttMinInput->callback((Fl_Callback*)rist_rtt_min_cb);
      } // Fl_Input* ristRttMinInput
      { ristRttMaxInput = new Fl_Input(765, 128, 92, 22, "RTT Max");
        ristRttMaxInput->callback((Fl_Callback*)rist_rtt_max_cb);
      } // Fl_Input* ristRttMaxInput
      { ristReorderBufferInput = new Fl_Input(765, 153, 92, 22, "Reorder Buffer");
        ristReorderBufferInput->callback((Fl_Callback*)rist_reorder_buffer_cb);
      } // Fl_Input* ristReorderBufferInput
      o->end();
    } // Fl_Group* o
    { btnStartStream = new Fl_Button(610, 203, 218, 22, "Start Stream");
      btnStartStream->callback((Fl_Callback*)startStream_cb);
    } // Fl_Button* btnStartStream
    { btnStopStream = new Fl_Button(335, 203, 218, 22, "Stop Stream");
      btnStopStream->callback((Fl_Callback*)stopStream_cb);
      btnStopStream->deactivate();
    } // Fl_Button* btnStopStream
    { statsGroup = new Fl_Group(1040, 25, 266, 200, "Stats");
      { bandwidthOutput = new Fl_Output(1135, 50, 165, 24, "Bandwidth");
      } // Fl_Output* bandwidthOutput
      { linkQualityOutput = new Fl_Output(1135, 76, 165, 24, "Link Quality");
      } // Fl_Output* linkQualityOutput
      { retransmittedPacketsOutput = new Fl_Output(1135, 101, 165, 24, "Retransmitted Packets");
      } // Fl_Output* retransmittedPacketsOutput
      { rttOutput = new Fl_Output(1135, 151, 165, 24, "RTT");
      } // Fl_Output* rttOutput
      { totalPacketsOutput = new Fl_Output(1135, 126, 165, 24, "Packets");
      } // Fl_Output* totalPacketsOutput
      { encodeBitrateOutput = new Fl_Output(1135, 201, 165, 24, "Encode Bitrate");
      } // Fl_Output* encodeBitrateOutput
      statsGroup->end();
    } // Fl_Group* statsGroup
    { logDisplay = new Fl_Text_Display(21, 246, 1294, 168, "Log");
    } // Fl_Text_Display* logDisplay
    { ristLogDisplay = new Fl_Text_Display(22, 431, 1293, 163, "RIST Log");
    } // Fl_Text_Display* ristLogDisplay
    mainWindow->end();
    mainWindow->resizable(mainWindow);
  } // Fl_Double_Window* mainWindow
}

void UserInterface::show(int argc, char **argv) {
  mainWindow->show(argc, argv);
}
